### ISSUE TITLE
Failed message are never retried nor sent to the failure transport

### ISSUE THREAD

**Issue by nkrewcun** [win32service/Win32ServiceBundle#17]
When a handler failed and should be retried, it doesn't. Instead, the message is just rejected.
The same happens when a message should be sent to the failure transport.

This is due to the following listeners not being called :
* Symfony\Component\Messenger\EventListener\SendFailedMessageForRetryListener
* Symfony\Component\Messenger\EventListener\SendFailedMessageToFailureTransportListener

**Comment by macintoshplus** [comment]
Fixed with release v2.0.3
